bibcite_entity.bibcite_contributor_category.*:
  type: config_entity
  label: 'Contributor category config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
