bibcite_entity.mapping.*:
  type: config_object
  label: 'Mapping between entity and format fields'
  mapping:
    format:
      type: string
      label: 'Format ID'
    types:
      type: sequence
      label: 'Types mapping'
      sequence:
        type: string
        label: 'Type'
    fields:
      type: sequence
      label: 'Fields mapping'
      sequence:
        type: string
        label: 'Field'
    indexes:
      type: sequence
      label: 'Fields indexes'
      sequence:
        type: string
        label: 'Indexes'
    dependencies:
      type: config_dependencies
      label: Dependencies
