<?php

namespace Drupal\knowledgemap\Plugin\Field\FieldType;


use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\image\Plugin\Field\FieldType\ImageItem;

/**
 * Plugin implementation of the 'knowledgemap_field_type' field type.
 *
 * @FieldType(
 *   id = "knowledgemap_field_type",
 *   label = @Translation("Knowledge Map field type"),
 *   description = @Translation("This field stores the knowledge map."),
 *   default_widget = "knowledgemap_widget",
 *   default_formatter = "knowledgemap_formatter",
 *   column_groups = {
 *     "file" = {
 *       "label" = @Translation("File"),
 *       "columns" = {
 *         "target_id", "width", "height"
 *       },
 *       "require_all_groups_for_translation" = TRUE
 *     },
 *     "alt" = {
 *       "label" = @Translation("Alt"),
 *       "translatable" = TRUE
 *     },
 *     "title" = {
 *       "label" = @Translation("Title"),
 *       "translatable" = TRUE
 *     },
 *   },
 *   list_class = "\Drupal\file\Plugin\Field\FieldType\FileFieldItemList",
 *   constraints = {"ReferenceAccess" = {}, "FileValidation" = {}}
 * )
 */
class KnowledgemapItem extends ImageItem {


  /**
   * @inheritDoc
   */
  public static function defaultStorageSettings() {
    return parent::defaultStorageSettings(); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public static function defaultFieldSettings() {
    return parent::defaultFieldSettings(); // TODO: Change the autogenerated stub
  }

  /**
   * Builds the default_image details element.
   *
   * @param array $element
   *   The form associative array passed by reference.
   * @param array $settings
   *   The field settings array.
   */
  protected function defaultImageForm(array &$element, array $settings) {
    parent::defaultImageForm($element, $settings); // TODO: Change the autogenerated stub
  }


  /**
   * {@inheritdoc}
   */
  public static function schema(FieldStorageDefinitionInterface $field_definition) {
    return parent::schema($field_definition); // TODO: Change the autogenerated stub
  }

}
