version: '3'
services:
  xnavi_d9_db:
    image: mariadb:10.5
    container_name: "${PROJECT_NAME}_mariadb"
    #command: --max_allowed_packet=32505856 #Set max_allowed_packet to 256M
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  # ports:
  #    - "3306:3306"
    volumes:
      - ../database:/var/lib/mysql
    restart: always
  xnavi_d9_drupal:
    depends_on:
      - xnavi_d9_db
    build: .
    container_name: "${PROJECT_NAME}_drupal"
    # ports:
    #  - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seminavi_backend_d9.entrypoints=http"
      - "traefik.http.routers.seminavi_backend_d9.rule=Host(`seminavi.ydns.eu`)"
      - "traefik.http.middlewares.seminavi_backend_d9-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.seminavi_backend_d9.middlewares=seminavi_backend_d9-https-redirect"
      - "traefik.http.routers.seminavi_backend_d9-secure.entrypoints=https"
      - "traefik.http.routers.seminavi_backend_d9-secure.rule=Host(`seminavi.ydns.eu`)"
      - "traefik.http.routers.seminavi_backend_d9-secure.tls=true"
      - "traefik.http.routers.seminavi_backend_d9-secure.tls.certresolver=http"
      - "traefik.http.routers.seminavi_backend_d9-secure.service=seminavi_backend_d9"
      - "traefik.http.services.seminavi_backend_d9.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    volumes:
      - ../docroot:/app
    networks:
      - proxy
      - default
    restart: always
  xnavi_d9_solr:
    image: solr:7.5
    container_name: "${PROJECT_NAME}_solr"
    #  ports:
    #  - "8983:8983"
    volumes:
      - ./solr_xnavi_config:/opt/solr/solr_xnavi_config
      - xnavi_d9_core:/opt/solr/server/solr/core
  xnavi_neo4j:
        image: neo4j:4.0.3
        container_name: "${PROJECT_NAME}_neo4j"
        #   ports:
        #    - "7475:7474"
        #    - "7688:7687"
        volumes:
          - ./neo4j/data:/data
          - ./neo4j/logs:/logs
          - ./neo4j/import/:/var/lib/neo4j/import
          - ./neo4j/plugins:/plugins
        environment:
          - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
          - NEO4J_dbms_default__listen__address=xnavi_neo4j
          - NEO4J_dbms_default__advertised__address=xnavi_neo4j
          - NEO4J_dbms_connector_bolt_listen__address=xnavi_neo4j:7687
          - NEO4J_dbms_connector_http_listen__address=xnavi_neo4j:7474
  xnavi_corenlp:
        image: graham3333/corenlp-complete
        container_name: "${PROJECT_NAME}_corenlp"
        #   ports:
        #  - "9000:9000"
  xnavi_python:
        container_name: "${PROJECT_NAME}_python"
        build: ./python
        volumes:
          - ./python:/app
        ports:
          - "5000:5000"
        depends_on:
          - xnavi_neo4j
          - xnavi_corenlp

volumes:
  #xnavi_d9_db_data:
  xnavi_d9_core:
networks:
  proxy:
    external:
      name: proxy
