version: '3'
services:
  xnavi_d9_db:
    image: mariadb:10.5
    container_name: "${PROJECT_NAME}_mariadb"
    #command: --max_allowed_packet=32505856 #Set max_allowed_packet to 256M
    environment:
      MYSQL_DATABASE: semi_navi_d9
      MYSQL_ROOT_PASSWORD: semi_navi_d9
    ports:
      - "3306:3306"
    volumes:
      - ../database:/var/lib/mysql
    restart: always
  xnavi_d9_drupal:
    depends_on:
      - xnavi_d9_db
    build: .
    container_name: "${PROJECT_NAME}_drupal"
    ports:
      - "8080:80"
    volumes:
      - ../docroot:/app
    restart: always
  xnavi_d9_solr:
    image: solr:7.5
    ports:
      - "8983:8983"
    volumes:
      - ./solr_xnavi_config:/opt/solr/solr_xnavi_config
      - xnavi_d9_core:/opt/solr/server/solr/core
  xnavi_neo4j:
        image: neo4j:4.0.3
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
          - ./neo4j/data:/data
          - ./neo4j/logs:/logs
          - ./neo4j/import/:/var/lib/neo4j/import
          - ./neo4j/plugins:/plugins
        environment:
          - NEO4J_AUTH=neo4j/test
          - NEO4J_dbms_default__listen__address=neo4j
          - NEO4J_dbms_default__advertised__address=neo4j
          - NEO4J_dbms_connector_bolt_listen__address=neo4j:7687
          - NEO4J_dbms_connector_http_listen__address=neo4j:7474
  xnavi_corenlp:
        image: graham3333/corenlp-complete
        ports:
          - "9000:9000"
  xnavi_python:
        build: ./python
        volumes:
          - ./python:/app
        ports:
          - "5000:5000"
        depends_on:
          - xnavi_neo4j
          - xnavi_corenlp
  
volumes:
  #xnavi_d9_db_data:
  xnavi_d9_core:
