bibcite_import.settings:
  type: config_object
  label: 'Common import settings'
  mapping:
    settings:
      type: mapping
      mapping:
        contributor_deduplication:
          type: boolean
          label: 'Contributor'
        keyword_deduplication:
          type: boolean
          label: 'Keyword'
