bibcite.bibcite_csl_style.*:
  type: config_entity
  label: 'CSL style config'
  mapping:
    id:
      type: string
      label: 'ID'
    parent:
      type: string
      label: 'Parent ID'
    status:
      type: boolean
      label: 'Status'
    label:
      type: label
      label: 'Label'
    csl:
      type: text
      label: 'CSL'
    updated:
      type: integer
      label: 'Updated time'
    custom:
      type: boolean
      label: 'Custom'
    url_id:
      type: string
      label: 'URL ID'
    uuid:
      type: string
